function [fitresult, gof] = ExpOnFit(time, y)
%ExpOnFit
%  Create a fit. of the form y=a-b*exp(-c*time)
%
%  Data for 'untitled fit 1' fit:
%      X Input : time
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jan-2021 11:10:35


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( time, y );
% Set up fittype and options.
ft = fittype( 'a-b*exp(-c*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [max(y) max(y)-min(y) 0.008];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'BGfit' );
subplot( 2, 1, 1 ); h = plot( fitresult, xData, yData );% Plot fit with data.
legend( h, 'Average Background vs. time', 'Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
xlabel( 'time', 'Interpreter', 'none' );ylabel( 'avBg', 'Interpreter', 'none' ); % Label axes
subplot( 2, 1, 2 );h = plot( fitresult, xData, yData, 'residuals' );% Plot residuals.
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
xlabel( 'time', 'Interpreter', 'none' );ylabel( 'avBg', 'Interpreter', 'none' );% Label axes




